---
platform: linux

image_resource:
  type: docker-image
  source: { repository: concourse/bosh-cli }

inputs:
  - name: source-code

outputs:
  - name: new-repo

run:
  path: source-code/gitclonerepo/tasks/clonerepo.sh
